### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by effigies** [MEDFormat/MEDPython#6]
Does MEDPython consider `import dhn_med_py` "linking" in the sense that any package that performs the import must be GPL-licensed?

This is the position taken by Mercurial (https://wiki.mercurial-scm.org/License), which requires non-GPL tools to use their CLI instead, so it's worth clarifying.

**Comment by MEDFormat** [comment]
Hi Chris,

Under those circumstances, no.  If integrating the c library into a compiled commercial product, then yes.  But even that fee is minimal, unless I need to get heavily involved.  Hope that answers the question.


Cheers, Matt

￼

Matt Stead
***@***.***

**Comment by effigies** [comment]
Thanks!
